version: '3.7'

services:
    redis-sessions:
        image: redis:6-alpine
        restart: unless-stopped
        volumes:
            - $PWD/redis.conf:/etc/redis/redis.conf
            - $PWD/persistence/redis-sessions:/data
        networks:
            - nest-boilerplate
    postgres-database:
        image: postgres:12-alpine
        restart: unless-stopped
        networks:
            - nest-boilerplate
        env_file:
            - .env
        volumes:
            - $PWD/persistence/postgres-database:/var/lib/postgresql/data
    nest:
        build:
            context: .
            target: development
            dockerfile: ./nest.Dockerfile
        networks:
            - nest-boilerplate
            - traefik
        restart: unless-stopped
        env_file:
            - .env
        depends_on:
            - redis-sessions
            - postgres-database
        volumes:
            - ./src:/usr/src/app/src # Enable hot reload in the app container
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nest-boilerplate.rule=Host(`${API_DOMAIN}`)"
            - "traefik.http.services.nest-boilerplate.loadbalancer.server.port=3000"
            - "traefik.http.routers.nest-boilerplate.tls.certresolver=letsencrypt-ovhdns"
            - "traefik.http.routers.nest-boilerplate.entrypoints=websecure"
    postgres-pgadmin:
        image: dpage/pgadmin4:latest
        restart: unless-stopped
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@domain.com
            - PGADMIN_DEFAULT_PASSWORD=SuperSecret
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - 127.0.0.1:8004:80
        networks:
            - nest-boilerplate
    redis-insight:
        image: redislabs/redisinsight:latest
        restart: unless-stopped
        volumes:
            - redisinsight:/db
        ports:
            - 127.0.0.1:8003:8001
        networks:
            - nest-boilerplate

networks:
    nest-boilerplate:
    traefik:
        name: traefik

volumes:
    redisinsight:
    pgadmin:
